### ISSUE TITLE
Make getxyz() a static Labware.py method?

### ISSUE THREAD

**Issue by bsubbaraman** [machineagency/science_jubilee#50]
### Feature enhancement details

Currently, `getxyz()` is a helper method in a new `utils.py` [file](https://github.com/machineagency/science_jubilee/blob/main/science_jubilee/utils.py), which I think is a better approach than re-writing that function for each tool (which is what I was doing before). 

Instead of a utils.py file, should we add `getxyz()` as a static method in `Labware.py`? It makes conceptual sense to me that we'd retrieve well coordinates using Labware.py, and we could replace all `utils.getxyz()` with `Labware.getxyz()`, and we could remove `utils.py`.

**Comment by MariaPoliti** [comment]
I agree. I have implemented the suggested changes and added final implementation of `_getxyz()` method as a staticmethod in :class:`Labware`. 

Closing this issue and merging these changes soon.
